name: CI - Security Scanning (Simplified)

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  security-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        service: [frontend, product_service, order_service]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Determine build context
        id: context
        run: |
          if [ "${{ matrix.service }}" = "frontend" ]; then
            echo "path=./frontend" >> $GITHUB_OUTPUT
          else
            echo "path=./backend/${{ matrix.service }}" >> $GITHUB_OUTPUT
          fi
      
      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: ${{ steps.context.outputs.path }}
          tags: ${{ matrix.service }}:${{ github.sha }}
          load: true
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ matrix.service }}:${{ github.sha }}
          format: 'sarif'
          output: 'trivy-${{ matrix.service }}.sarif'
          severity: 'CRITICAL,HIGH'
      
      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: trivy-${{ matrix.service }}.sarif
          category: trivy-${{ matrix.service }}
